services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin4:
    container_name: pgadmin4
    image: 'dpage/pgadmin4'
    ports:
      - "51051:80"
    restart: always
    env_file:
      - ./pgadmin.env
       
volumes:
  postgres: